#docker-compose build
#docker-compose up
#docker-compose down -v --remove-orphans

version: '3.7'

services:
    assets_orchestrator:
        container_name: assets_orchestrator
        ports:
            - 3001:3001
        build:
            context: .
            dockerfile: Dockerfile.assets
        links:
            - kafka
        networks:
            - backendnetwork
        env_file:
            - .env

    accounts_orchestrator:
        container_name: accounts_orchestrator
        ports:
            - 3002:3002
        build:
            context: ../../orl-main-micro-micro-service
            dockerfile: Dockerfile
        networks:
            - backendnetwork
        env_file:
            - ../../orl-main-micro-micro-service/.env

    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        networks:
            - backendnetwork
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        hostname: kafka
        networks:
            - backendnetwork
        ports:
            - 9092:9092
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=kafka
        depends_on:
            - zookeeper

networks:
    backendnetwork:
